name: sam
channels:
    - pytorch
    - conda-forge
dependencies:
    - cpuonly
    - imagecodecs
    - napari
    - pip
    - pooch
    - python-xxhash
    - python-elf >=0.4.8
    - pytorch
    - segment-anything
    - torchvision
    - torch_em >=0.6.0
    - tqdm
    - timm
    - pip:
        - git+https://github.com/SysCV/sam-hq.git
